### ISSUE TITLE
Release 1.9 into LVFS

### ISSUE THREAD

**Issue by fooishbar** [fwupd/aiaiai-firmware#1]
@nvmoeller Can you please release H05 v1.9 into the LVFS stream? It's publicly available through the Windows updater, and works fine for me after having manually sidegraded my 'H60' headset into H05 v1.6 firmware using fwupdtool, then using Windows to upgrade to 1.9. Thanks.

**Comment by nvmoeller** [comment]
Done! Thanks for the heads-up.
